import Link from 'next/link';
import { formatRefreshedAt } from '@/lib/snapshot';
import { loadBts } from '@/lib/bts';
import { BtsView } from '@/components/bts/BtsView';

export const dynamic = 'force-dynamic';

export default async function BtsPage() {
  let bts;
  try {
    bts = await loadBts();
  } catch {
    bts = null;
  }

  return (
    <main className="min-h-screen px-6 py-10 sm:px-10">
      <div className="mx-auto flex max-w-6xl flex-col gap-8">
        <header className="flex flex-col gap-2 sm:flex-row sm:items-baseline sm:justify-between">
          <div>
            <p className="text-xs font-medium uppercase tracking-wider text-zinc-500">
              Daybreak Health · BTS 2026
            </p>
            <h1 className="mt-1 text-3xl font-semibold tracking-tight text-zinc-900">
              BTS Readiness
            </h1>
          </div>
          <div className="flex flex-col items-start gap-1 sm:items-end">
            <Link href="/" className="text-xs font-medium text-zinc-500 hover:text-zinc-700">
              ← Back to EOY Dashboard
            </Link>
            {bts && (
              <p className="text-xs text-zinc-500">
                Refreshed {formatRefreshedAt(bts.refreshedAt)}
              </p>
            )}
          </div>
        </header>

        {bts ? (
          <BtsView data={bts} />
        ) : (
          <div className="rounded-lg border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-900">
            BTS readiness data isn’t available yet. It’s generated by the nightly refresh —
            check back after the next run.
          </div>
        )}
      </div>
    </main>
  );
}
